apiVersion: v1
kind: Service
metadata:
  name: mine-postgres
  namespace: default
spec:
  selector:
    app: mine-postgres
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
