apiVersion: v1
kind: Secret
metadata:
  name: mine-app-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: postgresql://mineuser:minepass@mine-postgres:5432/minedb
  SECRET_KEY: change-this-secret-key-in-production
  DB_PASSWORD: minepass
